// Spanish translation of SPPIGOT data
// Proper nouns kept in English: Center for Watershed Protection, EPA, SPPIGOT, Safer Choice,
// WaterSense, Clear Roads, Snow and Ice Management Association, Sustainable Salt Initiative,
// EPA Region 2.
const SPPIGOT_DATA = {
  "operations": [
    {
      "name": "Parques y Paisajismo",
      "description": "La gestión y el cuidado de árboles, césped y otra vegetación en parques públicos, campos de golf, áreas de conservación, espacios abiertos comunitarios y otras propiedades públicas. Específicamente, esto incluye la siembra, el corte de césped, la poda, la aplicación de fertilizantes/pesticidas, la gestión de residuos orgánicos, el riego y la gestión de residuos.",
      "pollutants": "Nutrientes (nitrógeno, fósforo) provenientes de fertilizantes; pesticidas; combustible e hidrocarburos provenientes de equipos de paisajismo a gasolina",
      "opportunities": "Proteger las áreas naturales de la conversión a otros usos previene la contaminación asociada con la escorrentía urbana. La transición a paisajes nativos reduce la escorrentía y requiere menos fertilizantes/pesticidas/agua, mientras que las prácticas de bajo mantenimiento del césped también reducen los residuos orgánicos y la necesidad de aplicaciones químicas/riego. La transición a equipos de mantenimiento eléctricos también reduce la contaminación por aceite y combustible debido a derrames."
    },
    {
      "name": "Mantenimiento Vial de Invierno",
      "description": "Planificación y despliegue de operaciones de prevención de hielo y deshielo en la infraestructura de transporte público para garantizar viajes seguros en condiciones invernales. Estas actividades afectan instalaciones de almacenamiento de sal, carreteras, estacionamientos, puentes, aceras y otros espacios de transporte público.",
      "pollutants": "Cloruros provenientes de la sal de carretera",
      "opportunities": "Cambios en los procesos, inversiones en equipos y calibración, alternativas a la sal de carretera y capacitación en mejores prácticas pueden ayudar a minimizar la cantidad de cloruros que ingresan a los cuerpos de agua, manteniendo la seguridad pública."
    },
    {
      "name": "Construcción y Mantenimiento",
      "description": "Planificación, diseño, construcción, mantenimiento y reparación de proyectos de infraestructura pública (por ejemplo, agua/aguas residuales/aguas pluviales, transporte, energía, telecomunicaciones, proyectos de restauración e instalaciones públicas).",
      "pollutants": "Sedimentos provenientes de suelos erosionados, pesticidas y nutrientes provenientes del mantenimiento de derechos de vía de transporte; hidrocarburos aromáticos policíclicos (HAPs) provenientes del sellador de pavimento a base de alquitrán de hulla; carbonos orgánicos volátiles (COVs) y solventes asociados con la pintura de pavimentos",
      "opportunities": "Minimizar las alteraciones del sitio y realizar inspecciones y mantenimiento regulares ayuda a prevenir la erosión de sedimentos, mientras que cambiar los materiales o procesos utilizados puede reducir la cantidad de contaminantes tóxicos usados, reduciendo el potencial de contaminación por aguas pluviales."
    },
    {
      "name": "Gestión de Vehículos y Flotas",
      "description": "Suministro de energía, mantenimiento, limpieza, reparación y almacenamiento de flotas de propiedad pública, como autobuses, barredoras de calles, equipos de construcción, patrullas, camiones de bomberos, vehículos municipales y autobuses escolares.",
      "pollutants": "Solventes (por ejemplo, desengrasantes, diluyentes de pintura), aceite y grasa, combustibles, detergentes y otros compuestos tóxicos asociados con la limpieza, mantenimiento y reparación de vehículos.",
      "opportunities": "Realizar inspecciones regulares de vehículos minimiza derrames y fugas, mientras que cambiar materiales o procesos reduce el potencial de contaminación por aguas pluviales. Convertir las flotas de gasolina a eléctricas también reduce la contaminación por aceite y combustible debido a derrames."
    },
    {
      "name": "Gestión de Instalaciones Públicas",
      "description": "Operación y mantenimiento de superficies duras exteriores de instalaciones de propiedad pública, como edificios municipales, patios de obras públicas y piscinas públicas.",
      "pollutants": "Diversos, incluyendo detergentes y solventes utilizados para la limpieza",
      "opportunities": "Cambiar los materiales o procesos utilizados para limpiar edificios, pavimentos y otros componentes de superficies duras puede reducir la cantidad de contaminantes tóxicos usados, reduciendo el potencial de contaminación por aguas pluviales. Inventariar los productos almacenados puede ayudar a minimizar la sobrecompra y el uso excesivo de productos químicos, reduciendo aún más el potencial de contaminación."
    },
    {
      "name": "Adquisiciones y Regulaciones",
      "description": "Desarrollo, adopción e implementación de políticas y regulaciones por parte de agencias municipales y territoriales o naciones tribales. Incluye políticas de adquisiciones, regulaciones que rigen el desarrollo del suelo, restricciones a la venta de ciertos productos y otros mecanismos de política. También incluye el uso de regulaciones existentes para fomentar o hacer cumplir iniciativas de prevención de la contaminación.",
      "pollutants": "Diversos",
      "opportunities": "Restringir la venta o el uso de productos específicos y/o crear desincentivos financieros mediante cambios regulatorios reduce el uso de contaminantes. Las políticas de compras verdes establecen estándares y procedimientos para seleccionar productos ambientalmente preferibles."
    }
  ],
  "benefitHeaders": [
    "Previene la contaminación por nutrientes",
    "Previene la contaminación por sedimentos",
    "Previene la contaminación por pesticidas",
    "Previene la contaminación por basura",
    "Previene la contaminación por cloruros",
    "Previene la contaminación por COVs",
    "Previene la contaminación por HAPs",
    "Previene la contaminación por hidrocarburos de petróleo",
    "Previene otros contaminantes tóxicos",
    "Ahorra dinero",
    "Reduce las emisiones de gases de efecto invernadero",
    "Conserva el agua"
  ],
  "pollutantBenefits": [
    "Previene la contaminación por nutrientes",
    "Previene la contaminación por sedimentos",
    "Previene la contaminación por pesticidas",
    "Previene la contaminación por basura",
    "Previene la contaminación por cloruros",
    "Previene la contaminación por COVs",
    "Previene la contaminación por HAPs",
    "Previene la contaminación por hidrocarburos de petróleo",
    "Previene otros contaminantes tóxicos"
  ],
  "otherBenefits": [
    "Ahorra dinero",
    "Reduce las emisiones de gases de efecto invernadero",
    "Conserva el agua"
  ],
  "questions": [
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad tiene programas enfocados en la preservación de bosques, humedales y otras áreas naturales?",
      "action": "Adoptar un programa para proteger permanentemente parcelas prioritarias del desarrollo mediante adquisición o servidumbres.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por sedimentos","Ahorra dinero","Reduce las emisiones de gases de efecto invernadero","Conserva el agua"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad tiene programas o planes enfocados en la reforestación en tierras públicas prioritarias?",
      "action": "Adoptar programas o planes que tengan como objetivo la implementación de proyectos de reforestación y plantación de árboles en superficies de césped o impermeables de propiedad pública (por ejemplo, un plan de cuenca, un objetivo y plan de cobertura arbórea urbana, o un plan de mitigación de islas de calor urbanas).",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por sedimentos","Ahorra dinero","Reduce las emisiones de gases de efecto invernadero","Conserva el agua"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad utiliza paisajismo de conservación, xerojardinería u otras prácticas de paisajismo nativo en propiedades públicas?",
      "action": "Utilizar paisajismo de conservación, xerojardinería u otras prácticas de paisajismo nativo en propiedades públicas para reducir la necesidad de fertilizantes, pesticidas y agua.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por pesticidas","Ahorra dinero","Reduce las emisiones de gases de efecto invernadero","Conserva el agua"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad tiene un plan integrado de manejo de plagas para garantizar que los pesticidas se utilicen únicamente como último recurso en propiedades públicas?",
      "action": "Utilizar el manejo integrado de plagas para controlar malezas y plagas de insectos en propiedades públicas. El MIP reduce o elimina el uso de pesticidas al priorizar métodos mecánicos sobre los químicos, utilizando pesticidas solo como último recurso.",
      "benefits": ["Previene la contaminación por pesticidas","Ahorra dinero"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad tiene procedimientos para garantizar que los pesticidas y fertilizantes se usen correctamente en propiedades públicas?",
      "action": "Implementar procedimientos y capacitación para garantizar que el personal y los contratistas de paisajismo manejen y apliquen correctamente fertilizantes y pesticidas para prevenir el uso excesivo y evitar derrames.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por pesticidas","Ahorra dinero"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad realiza pruebas de suelo anuales para calibrar las necesidades de fertilizante del césped?",
      "action": "Realizar pruebas regulares de suelo para determinar las necesidades nutricionales del césped y usar los resultados para seleccionar el tipo y la tasa de aplicación de fertilizante adecuados.",
      "benefits": ["Previene la contaminación por nutrientes","Ahorra dinero"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Los sistemas de riego están cuidadosamente diseñados para conservar el agua potable y proporcionar solo el agua que las plantas necesitan para sobrevivir?",
      "action": "Diseñar sistemas de riego para utilizar solo lo necesario para que las plantas sobrevivan. Los accesorios de riego de EPA WaterSense, como controladores de riego basados en clima o humedad del suelo, ayudan a conservar el agua, previniendo la escorrentía o la lixiviación de contaminantes por el riego excesivo.",
      "benefits": ["Previene la contaminación por nutrientes","Conserva el agua"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad utiliza equipos de paisajismo a batería en lugar de a gasolina?",
      "action": "Planificar el reemplazo de equipos de paisajismo a gasolina por equipos a batería.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Ahorra dinero","Reduce las emisiones de gases de efecto invernadero"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad ha instalado estaciones de recarga de hidratación en parques y otras propiedades públicas?",
      "action": "Instalar estaciones de recarga de hidratación en parques y instalaciones públicas para fomentar el uso de botellas reutilizables y reducir la contaminación por basura.",
      "benefits": ["Previene la contaminación por basura"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad utiliza pintura para campos deportivos certificada por Safer Choice?",
      "action": "Utilizar pintura menos tóxica para el marcado de campos deportivos. El sitio web Safer Choice de la EPA puede usarse para encontrar productos certificados.",
      "benefits": ["Previene la contaminación por COVs","Previene otros contaminantes tóxicos","Reduce las emisiones de gases de efecto invernadero"] },
    { "operation": "Parques y Paisajismo",
      "question": "¿Su comunidad utiliza arena, fibra de coco u otro material orgánico como relleno para campos deportivos de césped artificial?",
      "action": "Utilizar arena, fibra de coco u otro material orgánico como relleno para campos deportivos de césped artificial en lugar de caucho granulado.",
      "benefits": ["Previene la contaminación por cloruros","Previene la contaminación por HAPs","Previene otros contaminantes tóxicos","Reduce las emisiones de gases de efecto invernadero"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad tiene un plan de gestión de sal?",
      "action": "Adoptar un plan de gestión de sal que identifique las mejores prácticas de manejo para reducir los impactos ambientales negativos de la sal de carretera, cumpliendo con la obligación de la comunidad de proporcionar carreteras seguras, eficientes y rentables. El plan debe aplicarse a todo el personal de mantenimiento invernal, incluidos empleados y contratistas.",
      "benefits": ["Previene la contaminación por cloruros","Ahorra dinero"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad utiliza anti-hielo (es decir, aplica una pequeña cantidad de deshielo líquido o salmuera) justo antes de las nevadas previstas?",
      "action": "Utilizar anti-hielo, que consiste en aplicar una pequeña cantidad de deshielo líquido justo antes de la tormenta. Con esta pequeña cantidad de deshielo, ocurrirá una microcapa de fusión que ayudará a evitar que la nieve se adhiera al pavimento.",
      "benefits": ["Previene la contaminación por cloruros","Ahorra dinero"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad prioriza la remoción física de nieve antes de tratar las superficies con deshielos?",
      "action": "Utilizar arados y otros métodos físicos para remover la mayor cantidad posible de nieve y hielo antes de tratar con deshielos para reducir la cantidad de deshielo necesario.",
      "benefits": ["Previene la contaminación por cloruros"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad tiene pautas establecidas de tasa de aplicación de sal basadas en parámetros reconocidos de la industria?",
      "action": "Adoptar pautas de tasa de aplicación de sal alineadas con investigaciones reconocidas de la industria (por ejemplo, Clear Roads, Snow and Ice Management Association, Sustainable Salt Initiative).",
      "benefits": ["Previene la contaminación por cloruros"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad selecciona los materiales de deshielo y las tasas de aplicación basándose en pronósticos meteorológicos precisos y datos de estaciones de información meteorológica vial (por ejemplo, temperaturas del pavimento)?",
      "action": "Utilizar pronósticos meteorológicos precisos y estaciones de información meteorológica vial para aplicar sal solo cuándo y dónde sea necesario.",
      "benefits": ["Previene la contaminación por cloruros","Ahorra dinero"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad utiliza esparcidores de tasa variable y equipos eficientes de remoción de nieve para reducir el uso de sal?",
      "action": "Utilizar arados segmentados, arados secundarios, esparcidores de tasa variable y maquinaria bien mantenida para una limpieza más rápida y efectiva y para adaptarse a las condiciones de la carretera.",
      "benefits": ["Previene la contaminación por cloruros","Ahorra dinero"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad calibra los esparcidores utilizados para la aplicación de sal de carretera para mantener una tasa de aplicación constante?",
      "action": "Calibrar los esparcidores para evitar la sobreaplicación de deshielos.",
      "benefits": ["Previene la contaminación por cloruros","Ahorra dinero"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad mide y evalúa el uso de deshielo, las características de la tormenta y la calidad del servicio para refinar las prácticas de mantenimiento vial invernal con el tiempo?",
      "action": "Establecer métodos para monitorear y evaluar la compra y el uso de sal, la severidad del clima y la calidad del servicio, y utilizar estos datos para refinar las prácticas con el tiempo. Esto puede incluir el uso de tecnología de seguimiento de sal habilitada por GPS/ubicación automatizada de vehículos.",
      "benefits": ["Previene la contaminación por cloruros","Ahorra dinero"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad establece contratos de servicios de mantenimiento vial invernal como acuerdos basados en el desempeño?",
      "action": "Establecer contratos de servicios de mantenimiento vial invernal como acuerdos basados en el desempeño que incentiven la eficiencia en lugar de compensar por la cantidad o frecuencia de sal y otros materiales aplicados.",
      "benefits": ["Previene la contaminación por cloruros","Ahorra dinero"] },
    { "operation": "Mantenimiento Vial de Invierno",
      "question": "¿Su comunidad requiere y proporciona acceso a capacitación en aplicación de sal para operadores de arado y contratistas de mantenimiento invernal?",
      "action": "Requerir y proporcionar acceso a capacitación en aplicación de sal para operadores de arados de nieve y contratistas de mantenimiento invernal.",
      "benefits": ["Previene la contaminación por cloruros"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad ha promulgado una prohibición sobre la entrega de plásticos de un solo uso (por ejemplo, bolsas, pajitas, botellas, recipientes de poliestireno expandido) a los consumidores?",
      "action": "Prohibir todos los plásticos de un solo uso, o ciertos tipos de plásticos de un solo uso como bolsas o botellas plásticas, para abordar fuentes comunes de contaminación por basura en su comunidad.",
      "benefits": ["Previene la contaminación por basura"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad tiene medidas regulatorias para garantizar que los productos plásticos de un solo uso no se proporcionen de forma gratuita en el punto de venta al consumidor final?",
      "action": "Promulgar legislación que requiera a los establecimientos minoristas cobrar a los consumidores una cantidad establecida por productos plásticos de un solo uso, como bolsas plásticas.",
      "benefits": ["Previene la contaminación por basura"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad ha promulgado una prohibición sobre el uso de equipos de césped y paisajismo a gasolina, como sopladores de hojas, recortadoras, podadoras de setos, bordeadoras, sierras de extensión, motosierras y cortadoras de césped?",
      "action": "Promulgar una prohibición sobre el uso de equipos de césped y paisajismo a gasolina.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Reduce las emisiones de gases de efecto invernadero"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad ha promulgado legislación que prohíbe la venta de nuevos equipos de césped y paisajismo a gasolina?",
      "action": "Promulgar legislación que prohíba la venta de nuevos equipos de césped y paisajismo a gasolina.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad ha promulgado una prohibición sobre la venta de sellador de pavimento a base de alquitrán de hulla?",
      "action": "Promulgar legislación que prohíba la venta de sellador de pavimento a base de alquitrán de hulla para limitar la cantidad de hidrocarburos aromáticos policíclicos que ingresan a las aguas pluviales y los cuerpos de agua.",
      "benefits": ["Previene la contaminación por HAPs"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad ha promulgado una prohibición sobre la venta o el uso de fertilizante con fósforo para césped?",
      "action": "Promulgar legislación que prohíba la venta o el uso de fertilizante con fósforo en césped.",
      "benefits": ["Previene la contaminación por nutrientes"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad ha promulgado regulaciones de fertilizantes que establezcan límites de aplicación de nitrógeno para consumidores y aplicadores profesionales?",
      "action": "Promulgar regulaciones de fertilizantes que establezcan límites de aplicación de nitrógeno para consumidores y aplicadores profesionales para reducir el escurrimiento excesivo de nutrientes.",
      "benefits": ["Previene la contaminación por nutrientes"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad tiene una política de compras verdes que se compromete con compras ambientalmente preferibles utilizando estándares y procedimientos para seleccionar productos según criterios ambientales?",
      "action": "Desarrollar una política de compras verdes que coordine las compras para minimizar los impactos en la salud humana y el medio ambiente natural. Las políticas de compras verdes establecen estándares y procedimientos para seleccionar productos ambientalmente preferibles que van más allá de los materiales reciclados para considerar también las materias primas, los procesos de fabricación y la gestión al final de la vida útil.",
      "benefits": ["Previene la contaminación por basura","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos","Ahorra dinero","Reduce las emisiones de gases de efecto invernadero","Conserva el agua"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad tiene regulaciones para proteger bosques, humedales y otras áreas naturales de los impactos durante el desarrollo del suelo?",
      "action": "Adoptar regulaciones que minimicen la pérdida de bosques, humedales y áreas naturales durante el desarrollo del suelo.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por sedimentos","Reduce las emisiones de gases de efecto invernadero"] },
    { "operation": "Adquisiciones y Regulaciones",
      "question": "¿Su comunidad tiene regulaciones para minimizar la limpieza de terrenos y prevenir la erosión durante el desarrollo del suelo?",
      "action": "Adoptar regulaciones que minimicen la limpieza de terrenos y prevengan la erosión y sedimentación durante el proceso de construcción.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por sedimentos","Reduce las emisiones de gases de efecto invernadero"] },
    { "operation": "Gestión de Vehículos y Flotas",
      "question": "¿Su comunidad utiliza productos ecológicos para el lavado de vehículos?",
      "action": "Utilizar detergentes biodegradables, sin fosfatos y a base de agua para el lavado de flotas. El sitio web Safer Choice de la EPA puede usarse para buscar productos específicos para limpiar, proteger y eliminar la sal de los vehículos.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos"] },
    { "operation": "Gestión de Vehículos y Flotas",
      "question": "¿Su comunidad utiliza un sistema para limpiar piezas de vehículos que no requiere solventes?",
      "action": "Reemplazar la limpieza de piezas a base de solventes con métodos alternativos (por ejemplo, limpieza mecánica, lavadores enzimáticos, hornos de cocción).",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos"] },
    { "operation": "Gestión de Vehículos y Flotas",
      "question": "¿Su comunidad utiliza desengrasantes certificados por Safer Choice para limpiar piezas de vehículos?",
      "action": "Reemplazar solventes como desengrasantes con alternativas menos tóxicas (por ejemplo, cambiar de versiones a base de petróleo a versiones a base de agua). El sitio web Safer Choice de la EPA puede usarse para encontrar productos certificados.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos"] },
    { "operation": "Gestión de Vehículos y Flotas",
      "question": "¿Su comunidad inspecciona y mantiene regularmente los vehículos de la flota para minimizar las fugas de contaminantes?",
      "action": "Establecer procedimientos para inspeccionar y mantener regularmente los vehículos de la flota para minimizar las fugas de contaminantes (por ejemplo, combustible, líquido de frenos, anticongelante, aceite).",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por HAPs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos","Ahorra dinero"] },
    { "operation": "Gestión de Vehículos y Flotas",
      "question": "¿Su comunidad cambia los líquidos de los vehículos de la flota según sea necesario, utilizando los resultados de las inspecciones?",
      "action": "Cambiar los líquidos de los vehículos según sea necesario en lugar de un cronograma fijo para evitar el mantenimiento innecesario y el uso/derrame asociado de productos químicos.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por HAPs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos","Ahorra dinero"] },
    { "operation": "Gestión de Vehículos y Flotas",
      "question": "¿Su comunidad tiene procedimientos para reemplazar los vehículos a gasolina con vehículos híbridos o eléctricos?",
      "action": "Adoptar una política y procedimientos para reemplazar los vehículos de la flota a gasolina con vehículos híbridos o eléctricos.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Reduce las emisiones de gases de efecto invernadero"] },
    { "operation": "Gestión de Instalaciones Públicas",
      "question": "¿Su comunidad mantiene un inventario de los materiales almacenados y utilizados en cada instalación pública?",
      "action": "Mantener un inventario de todos los materiales almacenados y utilizados en instalaciones públicas para llevar un registro del uso de productos químicos y reducir compras innecesarias, uso excesivo y desperdicio.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por sedimentos","Previene la contaminación por pesticidas","Previene la contaminación por basura","Previene la contaminación por cloruros","Previene la contaminación por COVs","Previene la contaminación por HAPs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos","Ahorra dinero"] },
    { "operation": "Gestión de Instalaciones Públicas",
      "question": "¿Su comunidad utiliza métodos mecánicos o secos para limpiar superficies duras donde sea posible en lugar de usar productos químicos?",
      "action": "Utilizar métodos de limpieza mecánica o seca (por ejemplo, barrido) para limpiar superficies duras como edificios y pavimentos donde sea posible, para evitar el uso de detergentes y desengrasantes.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Conserva el agua"] },
    { "operation": "Gestión de Instalaciones Públicas",
      "question": "¿Su comunidad utiliza los productos menos tóxicos disponibles para limpiar edificios, pavimentos, piscinas y otras secciones de superficies duras de las instalaciones públicas?",
      "action": "Utilizar las alternativas menos tóxicas para la limpieza de instalaciones, como detergentes biodegradables, sin fosfatos y a base de agua para el lavado exterior de edificios, o pinturas, geles o aerosoles a base de agua para la eliminación de grafiti. El sitio web Safer Choice de la EPA puede usarse para buscar productos específicos de limpieza.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos"] },
    { "operation": "Gestión de Instalaciones Públicas",
      "question": "¿Su comunidad utiliza pinturas y revestimientos a base de agua o pinturas alternativas en lugar de los a base de aceite para uso exterior cuando sea apropiado?",
      "action": "Considerar pinturas a base de agua o alternativas (por ejemplo, cal, proteína de leche, pigmentos a base de arcilla y tierra) y revestimientos donde sea adecuado para reducir contaminantes tóxicos como compuestos orgánicos volátiles y eliminar la necesidad de solventes para la limpieza.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos"] },
    { "operation": "Gestión de Instalaciones Públicas",
      "question": "¿Su comunidad utiliza pruebas diarias del agua de la piscina para determinar las necesidades de productos químicos?",
      "action": "Utilizar los resultados de las pruebas de agua para guiar el mantenimiento de la piscina y prevenir la sobreaplicación de productos químicos, lo que puede llevar a la producción de subproductos de desinfección difíciles de eliminar y que pueden terminar en aguas pluviales.",
      "benefits": ["Previene la contaminación por cloruros","Previene otros contaminantes tóxicos","Ahorra dinero"] },
    { "operation": "Gestión de Instalaciones Públicas",
      "question": "¿Su comunidad declora el agua de la piscina antes de descargarla al final de la temporada?",
      "action": "Seguir las mejores prácticas para declorar el agua de las piscinas públicas mediante exposición a rayos UV antes de descargarla al final de la temporada.",
      "benefits": ["Previene la contaminación por cloruros","Previene otros contaminantes tóxicos"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad tiene regulaciones para minimizar la pérdida de árboles y bosques durante las actividades de construcción pública?",
      "action": "Modificar los códigos y ordenanzas locales para que los desarrollos minimicen la pérdida de árboles y bosques.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por sedimentos","Reduce las emisiones de gases de efecto invernadero"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad tiene regulaciones para minimizar la limpieza de terrenos, la erosión y la sedimentación durante los proyectos públicos de construcción, mantenimiento y reparación?",
      "action": "Adoptar una ordenanza local de control de erosión y sedimentos para minimizar la erosión del suelo durante las actividades de construcción.",
      "benefits": ["Previene la contaminación por sedimentos"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad inspecciona y mantiene regularmente los equipos de construcción y mantenimiento para prevenir fugas de contaminantes?",
      "action": "Establecer procedimientos para inspeccionar y mantener regularmente los equipos de construcción y mantenimiento para minimizar las fugas de contaminantes.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por HAPs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad tiene un programa para inspeccionar, mantener y reparar regularmente las instalaciones e infraestructura de gestión de aguas pluviales?",
      "action": "Implementar procedimientos para inspeccionar, mantener y reparar regularmente las instalaciones e infraestructura de gestión de aguas pluviales para prevenir fallas que contribuyan a la erosión u otra descarga de contaminación.",
      "benefits": ["Previene la contaminación por sedimentos","Ahorra dinero"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad utiliza alternativas menos tóxicas a los selladores de pavimento a base de alquitrán de hulla para proyectos públicos?",
      "action": "Utilizar alternativas a los selladores de pavimento a base de alquitrán de hulla (por ejemplo, emulsiones asfálticas sin alquitrán de hulla, acrílicos, selladores de origen biológico, emulsiones modificadas con polímeros) en proyectos públicos de construcción para reducir los HAPs.",
      "benefits": ["Previene la contaminación por HAPs"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad utiliza pinturas y revestimientos a base de agua o pinturas alternativas en lugar de las a base de aceite para el marcado de carreteras y estacionamientos públicos cuando sea apropiado?",
      "action": "Considerar pinturas a base de agua o alternativas (por ejemplo, cal, proteína de leche, pigmentos a base de arcilla y tierra) y revestimientos donde sea adecuado para reducir contaminantes tóxicos como compuestos orgánicos volátiles y eliminar la necesidad de solventes para la limpieza.",
      "benefits": ["Previene la contaminación por COVs","Previene la contaminación por hidrocarburos de petróleo","Previene otros contaminantes tóxicos"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad utiliza el manejo integrado de plagas para el mantenimiento de los derechos de vía públicos para garantizar que los pesticidas se utilicen únicamente como último recurso?",
      "action": "Utilizar el manejo integrado de plagas para controlar malezas y plagas a lo largo de los bordes de las carreteras públicas.",
      "benefits": ["Previene la contaminación por pesticidas","Ahorra dinero"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad tiene procedimientos para garantizar que los pesticidas y fertilizantes se usen correctamente en los derechos de vía públicos?",
      "action": "Implementar procedimientos y capacitación para garantizar que el personal de obras públicas y los contratistas manejen y apliquen correctamente fertilizantes y pesticidas para prevenir el uso excesivo y evitar derrames.",
      "benefits": ["Previene la contaminación por nutrientes","Previene la contaminación por pesticidas","Ahorra dinero"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad mantiene y aplica estándares de diseño y mantenimiento para caminos no pavimentados públicos y privados (es decir, tierra, grava, roca nativa u otra superficie no duradera)?",
      "action": "Integrar estándares de diseño y mantenimiento para caminos no pavimentados en el proceso de desarrollo del suelo.",
      "benefits": ["Previene la contaminación por sedimentos","Ahorra dinero"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad tiene un programa enfocado en el inventario, la inspección y el mantenimiento de caminos no pavimentados?",
      "action": "Implementar procedimientos para inventariar los caminos no pavimentados existentes, realizar inspecciones regulares de su condición y realizar el mantenimiento para prevenir o abordar problemas de erosión.",
      "benefits": ["Previene la contaminación por sedimentos","Ahorra dinero"] },
    { "operation": "Construcción y Mantenimiento",
      "question": "¿Su comunidad está trabajando para que los caminos existentes cumplan con los estándares de caminos no pavimentados (o aborde de otra manera la erosión en los caminos no pavimentados existentes)?",
      "action": "Abordar los problemas de erosión más graves en caminos no pavimentados mediante reperfilado, mejoras de drenaje y estabilización de pendientes.",
      "benefits": ["Previene la contaminación por sedimentos"] }
  ]
};
